<?php

/*
	userAgentString.php - array of user agent strings to keep em' on their toes
*/

$userAgentString = array(
	"amaya/9.52 libwww/5.4.0",
	"amaya/11.1 libwww/5.4.0",
	"Amiga-AWeb/3.5.07 beta",
	"AmigaVoyager/3.4.4 (MorphOS/PPC native)",
	"AmigaVoyager/2.95 (compatible; MC680x0; AmigaOS)",
	"Mozilla/4.0 (compatible; MSIE 7.0; AOL 9.0; Windows NT 5.1; .NET CLR 1.1.4322; Zango 10.1.181.0)",
	"Mozilla/4.0 (compatible; MSIE 6.0; AOL 6.0; Windows NT 5.1)",
	"Mozilla/4.0 (compatible; MSIE 7.0; AOL 9.5; AOLBuild 4337.35; Windows NT 5.1; .NET CLR 1.1.4322; .NET CLR 2.0.50727)",
	"Mozilla/4.0 (compatible; MSIE 7.0; AOL 7.0; Windows NT 5.1; FunWebProducts)",
	"Mozilla/4.0 (compatible; MSIE 6.0; AOL 8.0; Windows NT 5.1; SV1)",
	"Mozilla/5.0 (X11; U; Linux; en-US) AppleWebKit/527+ (KHTML, like Gecko, Safari/419.3) Arora/0.6",
	"Mozilla/5.0 (X11; U; Linux; C -) AppleWebKit/523.15 (KHTML, like Gecko, Safari/419.3) Arora/0.5",
	"Mozilla/5.0 (Windows; U; Windows NT 5.1; zh-CN) AppleWebKit/523.15 (KHTML, like Gecko, Safari/419.3) Arora/0.3 (Change: 287 c9dfb30)",
	"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; JyxoToolbar1.0; Embedded Web Browser from: http://bsalsa.com/; Avant Browser; .NET CLR 2.0.50727; .NET CLR 3.0.04506.648; .NET CLR 3.5.21022; .NET CLR 1.1.4322)",
	"Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; GTB5; Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1) ; Avant Browser)",
	"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; Avant Browser; Avant Browser; .NET CLR 1.1.4322; .NET CLR 2.0.50727; InfoPath.1)",
	"Mozilla/5.0 (X11; 78; CentOS; US-en) AppleWebKit/527+ (KHTML, like Gecko) Bolt/0.862 Version/3.0 Safari/523.15",
	"Mozilla/5.0 (Macintosh; U; Intel Mac OS X Mach-O; en; rv:1.8.1.12) Gecko/20080206 Camino/1.5.5",
	"Mozilla/5.0 (Macintosh; U; PPC Mac OS X Mach-O; en-US; rv:1.8.0.10) Gecko/20070228 Camino/1.0.4",
	"Mozilla/5.0 (Macintosh; U; PPC Mac OS X Mach-O; en; rv:1.8.1.4pre) Gecko/20070511 Camino/1.6pre",
	"Mozilla/5.0 (Macintosh; U; PPC Mac OS X Mach-O; en-US; rv:1.7.2) Gecko/20040825 Camino/0.8.1",
	"Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/525.19 (KHTML, like Gecko) Chrome/1.0.154.53 Safari/525.19",
	"Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/525.19 (KHTML, like Gecko) Chrome/1.0.154.36 Safari/525.19",
	"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 1.1.4322; Crazy Browser 2.0.1)",
	"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; Crazy Browser 1.0.5; .NET CLR 1.1.4322; InfoPath.1)",
	"Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; .NET CLR 1.1.4322; .NET CLR 2.0.50727; Crazy Browser 3.0.0 Beta2)",
	"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; Deepnet Explorer 1.5.0; .NET CLR 1.0.3705)",
	"Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_5_6; en-us) AppleWebKit/525.27.1 (KHTML, like Gecko) Demeter/1.0.9 Safari/125",
	"Dillo/0.8.5",
	"Dillo/2.0",
	"Doris/1.15 [en] (Symbian)",
	"ELinks/0.13.GIT (textmode; Linux 2.6.22-2-686 i686; 148x68-3)",
	"ELinks/0.9.3 (textmode; Linux 2.6.11 i686; 79x24)",
	"Enigma Browser",
	"Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.7.3) Gecko/20041007 Epiphany/1.4.7",
	"Mozilla/5.0 (X11; U; Linux i686; en; rv:1.8.1.12) Gecko/20080208 (Debian-1.8.1.12-2) Epiphany/2.20",
	"Mozilla/5.0 (Windows; U; Win98; en-US; rv:1.5) Gecko/20031007 Firebird/0.7",
	"Mozilla/5.0 (Windows; U; Win95; en-US; rv:1.5) Gecko/20031007 Firebird/0.7",
	"Mozilla/5.0 (Windows; U; WinNT4.0; en-US; rv:1.7.9) Gecko/20050711 Firefox/1.0.5",
	"Mozilla/5.0 (X11; U; SunOS sun4u; en-US; rv:1.9b5) Gecko/2008032620 Firefox/3.0b5",
	"Mozilla/5.0 (X11; U; OpenBSD i386; en-US; rv:1.8.0.5) Gecko/20060819 Firefox/1.5.0.5",
	"Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.5; en-US; rv:1.9.1b3) Gecko/20090305 Firefox/3.1b3 GTB5",
	"Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.8.1.12) Gecko/20080214 Firefox/2.0.0.12",
	"Mozilla/5.0 (Windows; U; Windows NT 5.0; es-ES; rv:1.8.0.3) Gecko/20060426 Firefox/1.5.0.3",
	"Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.5; ko; rv:1.9.1b2) Gecko/20081201 Firefox/3.1b2",
	"Mozilla/5.0 (Windows; U; Windows NT 5.1; cs; rv:1.9.0.8) Gecko/2009032609 Firefox/3.0.8",
	"Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.0.8) Gecko/2009033017 GranParadiso/3.0.8",
	"Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US; rv:1.9.1b4pre) Gecko/20090311 Shiretoko/3.1b4pre",
	"Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.9.1b3pre) Gecko/20090109 Shiretoko/3.1b3pre",
	"Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US; rv:1.9.0.2) Gecko/2008092122 Firefox/3.0.2 Flock/2.0b3",
	"Mozilla/5.0 (Macintosh; U; PPC Mac OS X Mach-O; en-US; rv:1.8.0.1) Gecko/20060314 Flock/0.5.13.2",
	"Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/525.13 (KHTML, like Gecko) Fluid/0.9.4 Safari/525.13",
	"Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.7.12) Gecko/20050929 Galeon/1.3.21",
	"Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.0.8) Gecko/20090327 Galeon/2.0.7",
	"Mozilla/3.0 (x86 [cs] Windows NT 5.1; Sun)",
	"HotJava/1.1.2 FCS",
	"Mozilla/5.1 (X11; U; Linux i686; en-US; rv:1.8.0.3) Gecko/20060425 SUSE/1.5.0.3-7 Hv3/alpha",
	"IBrowse/2.3 (AmigaOS 3.9)",
	"Mozilla/5.0 (compatible; IBrowse 3.0; AmigaOS4.0)",
	"iCab/3.0.2 (Macintosh; U; PPC Mac OS X)",
	"iCab/4.0 (Macintosh; U; Intel Mac OS X)",
	"Mozilla/4.5 (compatible; iCab 2.9.1; Macintosh; U; PPC)",
	"Mozilla/5.0 (Java 1.6.0_01; Windows XP 5.1 x86; en) ICEbrowser/v6_1_2",
	"ICE Browser/5.05 (Java 1.4.0; Windows 2000 5.0 x86)",
	"Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.8.1.9) Gecko/20071030 Iceape/1.1.6 (Debian-1.1.6-3)",
	"Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.8.1.8) Gecko/20071008 Iceape/1.1.5 (Ubuntu-1.1.5-1ubuntu0.7.10)",
	"Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.8.1.1) Gecko/20061205 Iceweasel/2.0.0.1 (Debian-2.0.0.1+dfsg-4)",
	"Mozilla/5.0 (X11; U; Linux i686; it; rv:1.9.0.5) Gecko/2008122011 Iceweasel/3.0.5 (Debian-3.0.5-1)",
	"Mozilla/5.0 (X11; U; Linux i686; de; rv:1.9.0.5) Gecko/2008122011 Iceweasel/3.0.5 (Debian-3.0.5-1)",
	"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 1.0.3705; .NET CLR 1.1.4322; Media Center PC 4.0; .NET CLR 2.0.50727)",
	"Mozilla/4.0 (compatible; MSIE 5.0; Windows NT;)",
	"Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.0; Trident/4.0; GTB5; SLCC1; .NET CLR 2.0.50727; Media Center PC 5.0; .NET CLR 3.0.04506; InfoPath.2; OfficeLiveConnector.1.3; OfficeLivePatch.0.0)",
	"Mozilla/4.0 (Windows; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 2.0.50727)",
	"Mozilla/4.0 (Mozilla/4.0; MSIE 7.0; Windows NT 5.1; FDM; SV1; .NET CLR 3.0.04506.30)",
	"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; iRider 2.21.1108; FDM)",
	"Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US) AppleWebKit/528.7 (KHTML, like Gecko) Iron/1.0.155.0 Safari/528.7",
	"Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/525.19 (KHTML, like Gecko) Iron/0.2.152.0 Safari/12081672.525",
	"Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US) AppleWebKit/528.5 (KHTML, like Gecko) Iron/0.4.155.0 Safari/528.5",
	"Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.0.5) Gecko/20060706 K-Meleon/1.0",
	"Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US; rv:1.8.1.19) Gecko/20081217 K-Meleon/1.5.2",
	"Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.0.6) Gecko/20060731 K-Ninja/2.0.2",
	"Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.2pre) Gecko/20070215 K-Ninja/2.1.1",
	"Mozilla/5.0 (Windows; U; Windows NT 5.1; zh-CN; rv:1.9) Gecko/20080705 Firefox/3.0 Kapiko/3.0",
	"Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.0.8) Gecko Fedora/1.9.0.8-1.fc10 Kazehakase/0.5.6",
	"Mozilla/5.0 (X11; Linux i686; U;) Gecko/20070322 Kazehakase/0.4.5",
	"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; KKman2.0)",
	"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; KKMAN3.2)",
	"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; KKman3.0)",
	"Mozilla/5.0 (compatible; Konqueror/2.2.1; Linux)",
	"Mozilla/5.0 (compatible; Konqueror/3.5; SunOS)",
	"Mozilla/5.0 (compatible; Konqueror/4.1; OpenBSD) KHTML/4.1.4 (like Gecko)",
	"Mozilla/5.0 (compatible; Konqueror/3.1-rc5; i686 Linux; 20020712)",
	"Links (2.1pre18; Linux 2.4.31 i686; 100x37)",
	"Links (2.1; Linux 2.6.18-gentoo-r6 x86_64; 80x24)",
	"Links (2.2; Linux 2.6.25-gentoo-r9 sparc64; 166x52)",
	"Links (0.96; Linux 2.4.20-18.7 i586)",
	"Links (0.98; Win32; 80x25)",
	"Mozilla/4.0 (compatible; MSIE 6.0; Windows XP 5.1) Lobo/0.98.4",
	"Mozilla/4.0 (compatible; Lotus-Notes/6.0; Windows-NT)",
	"Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/528+ (KHTML, like Gecko, Safari/528.0) Lunascape/5.0.2.0",
	"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0; .NET CLR 1.1.4322; Lunascape 2.1.3)",
	"Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.1b3pre) Gecko/2008 Lunascape/4.9.9.98",
	"Lynx/2.8.3dev.6 libwww-FM/2.14",
	"Lynx/2.8.5dev.16 libwww-FM/2.14 SSL-MM/1.4.1 OpenSSL/0.9.7a",
	"Lynx/2.8.6rel.4 libwww-FM/2.14 SSL-MM/1.4.1 GNUTLS/1.6.3",
	"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; MyIE2)",
	"Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0; .NET CLR 2.0.50727; MAXTHON 2.0)",
	"Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; SV1; Maxthon; .NET CLR 1.1.4322)",
	"Midori/0.1.5 (X11; Linux; U; en-gb) WebKit/532+",
	"Mozilla/5.0 (Windows; U; Windows NT 5.0; it-IT; rv:1.7.12) Gecko/20050915",
	"Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.0.1) Gecko/20020919",
	"Mozilla/5.0 (Windows; U; Windows NT 5.0; en-US; rv:1.2.1; MultiZilla v1.1.32 final) Gecko/20021130",
	"Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.4; MultiZilla v1.5.0.0f) Gecko/20030624",
	"NCSA_Mosaic/3.0 (Windows 95)",
	"NCSA_Mosaic/2.6 (X11; SunOS 4.1.3 sun4m)",
	"NCSA_Mosaic/2.0 (Windows 3.1)",
	"Mozilla/3.01 (compatible; Netbox/3.5 R92; Linux 2.2)",
	"Mozilla/4.0 (compatible; MSIE 5.01; Windows NT 5.0; NetCaptor 6.5.0RC1)",
	"Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US; rv:1.8.1.12) Gecko/20080219 Firefox/2.0.0.12 Navigator/9.0.0.6",
	"Mozilla/4.08 [en] (WinNT; U ;Nav)",
	"Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.0.2) Gecko/20030208 Netscape/7.02",
	"Mozilla/3.0 (Win95; I)",
	"Mozilla/4.51 [en] (Win98; U)",
	"Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.7.5) Gecko/20060127 Netscape/8.1",
	"Mozilla/4.04 [en] (X11; I; IRIX 5.3 IP22)",
	"Mozilla/5.0 (Windows; U; Win 9x 4.90; de-DE; rv:0.9.2) Gecko/20010726 Netscape6/6.1",
	"NetSurf/1.2 (Linux; i686)",
	"NetSurf/2.0 (RISC OS; armv3l)",
	"Mozilla/4.7 (compatible; OffByOne; Windows 2000)",
	"Mozilla/4.7 (compatible; OffByOne; Windows 98)",
	"Mozilla/5.0 (Macintosh; U; PPC Mac OS X; en-US) AppleWebKit/420+ (KHTML, like Gecko, Safari) OmniWeb/v595",
	"Mozilla/4.5 (compatible; OmniWeb/4.1.1-v424.6; Mac_PowerPC)",
	"OmniWeb/2.7-beta-3 OWF/1.0",
	"Mozilla/4.0 (compatible; MSIE 5.0; Windows NT 4.0) Opera 6.01 [en]",
	"Opera/9.02 (Windows XP; U; ru)",
	"Opera/9.70 (Linux i686 ; U; en) Presto/2.2.1",
	"Mozilla/4.0 (compatible; MSIE 5.0; Windows 98) Opera 5.12 [en]",
	"Opera/7.03 (Windows NT 5.0; U) [en]",
	"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; en) Opera 9.24",
	"Opera/6.0 (Windows 2000; U) [fr]",
	"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1) Opera 7.10 [en]",
	"Opera/9.51 (Macintosh; Intel Mac OS X; U; en)",
	"Opera/5.11 (Windows 98; U) [en]",
	"Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.0.6) Gecko/2009022300 Firefox/3.0.6 Orca/1.1 build 1",
	"Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.0.7) Gecko/2009030821 Firefox/3.0.7 Orca/1.1 build 2",
	"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; PhaseOut-www.phaseout.net)",
	"Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.4a) Gecko/20030411 Phoenix/0.5",
	"Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.2b) Gecko/20021029 Phoenix/0.4",
	"Mozilla/5.0 (Windows; U; Windows NT 5.1; cs-CZ) AppleWebKit/523.15 (KHTML, like Gecko) Version/3.0 Safari/523.15",
	"Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/125.2 (KHTML, like Gecko) Safari/125.7",
	"Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US) AppleWebKit/528.16 (KHTML, like Gecko) Version/4.0 Safari/528.16",
	"Mozilla/5.0 (Macintosh; U; PPC Mac OS X; fi-fi) AppleWebKit/420+ (KHTML, like Gecko) Safari/419.3",
	"Mozilla/5.0 (Macintosh; U; PPC Mac OS X; en-us) AppleWebKit/312.8 (KHTML, like Gecko) Safari/312.6",
	"Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_5_6; it-it) AppleWebKit/528.16 (KHTML, like Gecko) Version/4.0 Safari/528.16",
	"Mozilla/5.0 (Windows; U; Win 9x 4.90; en-GB; rv:1.8.1.6) Gecko/20070802 SeaMonkey/1.1.4",
	"Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US; rv:1.9.1b3pre) Gecko/20081208 SeaMonkey/2.0a3pre",
	"Mozilla/5.0 (BeOS; U; BeOS BePC; en-US; rv:1.9a1) Gecko/20060702 SeaMonkey/1.5a",
	"Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.5; en-US; rv:1.9.1b3pre) Gecko/20081202 SeaMonkey/2.0a2",
	"Mozilla/5.0 (Macintosh; U; Intel Mac OS X; en-US; rv:1.8.1.13) Gecko/20080313 SeaMonkey/1.1.9",
	"Mozilla/5.0 (X11; U; Linux i686; rv:1.9.1a2pre) Gecko/20080824052448 SeaMonkey/2.0a1pre",
	"Mozilla/5.0 (Macintosh; U; PPC Mac OS X; en) AppleWebKit/417.9 (KHTML, like Gecko, Safari) Shiira/1.1",
	"Mozilla/5.0 (Macintosh; U; Intel Mac OS X; fr) AppleWebKit/418.9.1 (KHTML, like Gecko) Shiira Safari/125",
	"Mozilla/5.0 (Macintosh; U; PPC Mac OS X; ja-jp) AppleWebKit/419 (KHTML, like Gecko) Shiira/1.2.3 Safari/125",
	"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1) Sleipnir/2.8.1",
	"Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; .NET CLR 1.1.4322; InfoPath.1; .NET CLR 2.0.50727) Sleipnir/2.8.4",
	"Mozilla/5.0 (Macintosh; U; PPC Mac OS X; en-us) AppleWebKit/125.5.7 (KHTML, like Gecko) SunriseBrowser/0.853",
	"Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_4_11; en) AppleWebKit/525.18 (KHTML, like Gecko) Sunrise/1.7.4 like Safari/4525.22",
	"Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.0.10pre) Gecko/2009041814 Firefox/3.0.10pre (Swiftfox)",
	"w3m/0.5.2",
	"w3m/0.5.1",
	"Mozilla/3.0 (compatible; AvantGo 3.2)",
	"User-Agent: Mozilla/3.0 (compatible; AvantGo 5.2; FreeBSD)",
	"GetRight/3.2",
	"Mozilla/4.5 (compatible; HTTrack 3.0x; Windows 98)",
	"iSiloX/4.37 Windows/32",
	"JoBo/1.4",
	"Offline Explorer/1.4",
	"Offline Explorer/2.5",
	"SiteSucker/1.6.9",
	"Teleport Pro/1.2x",
	"WebCopier v4.2",
	"WebCopier v3.0",
	"WebZIP/7.0 (http://www.spidersoft.com)",
	"WebZIP/3.5 (http://www.spidersoft.com)",
	"Wget/1.10.1 (Red Hat modified)",
	"Wget/1.5.3",
	"BlackBerry8820/4.5.0.110 Profile/MIDP-2.0 Configuration/CLDC-1.1 VendorID/102",
	"BlackBerry8330m/4.5.0.131 Profile/MIDP-2.0 Configuration/CLDC-1.1 VendorID/104",
	"BlackBerry9000/4.6.0.126 Profile/MIDP-2.0 Configuration/CLDC-1.1 VendorID/120",
	"BlackBerry8100/4.5.0.124 Profile/MIDP-2.0 Configuration/CLDC-1.1 VendorID/100",
	"BlackBerry9530/4.7.0.76 Profile/MIDP-2.0 Configuration/CLDC-1.1 VendorID/126",
	"UPG1 UP/4.0 (compatible; Blazer 1.0)",
	"Palm680/RC1 Mozilla/4.0 (compatible; MSIE 6.0; Windows 98; PalmSource/Palm-D053; Blazer/4.5) 16;320x320 UP.Link/6.3.1.17.06.3.1.17.0",
	"Mozilla/4.0 (compatible; MSIE 6.0; Windows 98; PalmSource/Palm-TunX; Blazer/4.3) 16;320x448",
	"Mozilla/5.0 (X11; U; Linux armv7l; en-US; rv:1.9.2a1pre) Gecko/20090322 Fennec/1.0b2pre",
	"Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.1b2pre) Gecko/20081015 Fennec/1.0a1",
	"Mozilla/4.0 (compatible; MSIE 6.0; Windows CE; IEMobile 7.11) 320x240; VZW; Motorola-Q9c; Windows Mobile 6.1 Standard",
	"8900a/1.2 Mozilla/4.0 (compatible; MSIE 6.0; Windows CE; IEMobile 7.6)",
	"HTC_P4550/TYTN_II Mozilla/4.0 (compatible; MSIE 6.0; Windows CE; IEMobile 7.11)",
	"Mozilla/5.0 (X11; U; Linux armv6l; rv: 1.8.1.5pre) Gecko/20070619 Minimo/0.020",
	"Mozilla/5.0 (Windows; U; Windows CE 5.1; rv:1.8.1a3) Gecko/20060610 Minimo/0.016",
	"Mozilla/4.0 (PSP (PlayStation Portable); 2.00)",
	"Amoi 8709/R14.4 NF-Browser/3.4",
	"Mozilla/4.0 (PDA; PalmOS/sony/model prmr/Revision:1.1.54 (en)) NetFront/3.0",
	"Mozilla/4.0 (PDA; Windows CE/1.0.1) NetFront/3.0",
	"Mozilla/4.08 (Windows; Mobile Content Viewer/1.0) NetFront/3.2",
	"LG-CU720/V1.0g Obigo/Q05A Profile/MIDP-2.0 Configuration/CLDC-1.1 UP.Link/6.3.0.0.0",
	"Samsung-SPHA900 AU-MIC-A900/2.0 MMP/2.0 Profile/MIDP-2.0 Configuration/CLDC-1.1",
	"Samsung-SPHA920 AU-MIC-A920/2.0 MMP/2.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 Novarra-Vision/7.3",
	"LG-KC550 Teleca/WAP2.0 MIDP-2.0/CLDC-1.1",
	"UP.Browser/3.04-TS14 UP.Link/3.4.4",
	"UP.Browser/7.0.2.3.119 (GUI) MMP/2.0 Push/PO",
	"KWC-S1300/ UP.Browser/7.2.6.1.839 (GUI) MMP/2.0",
	"LG-LX600 Polaris/6.0 MMP/2.0 Profile/MIDP-2.1 Configuration/CLDC-1.1",
	"SonyEricssonK750i/R1L Browser/SEMC-Browser/4.2 Profile/MIDP-2.0 Configuration/CLDC-1.1",
	"SonyEricssonK750i/R1CA/SN352557010359373 Browser/SEMC-Browser/4.2 Profile/MIDP-2.0 Configuration/CLDC-1.1",
	"curl 7.16.1 (i386-portbld-freebsd6.2) libcurl/7.16.1 OpenSSL/0.9.7m zlib/1.2.3",
	"UniversalFeedParser/4.1 +http://feedparser.org/",
	"Jakarta Commons-HttpClient/3.0-rc3",
	"Jakarta Commons-HttpClient/2.0",
	"Java/1.4.2_08",
	"Java1.3.1_06",
	"Java/1.6.0_03",
	"libwww-perl/5.812",
	"libwww-perl/5.53",
	"lwp-trivial/1.41",
	"lwp-trivial/1.35",
	"LWP::Simple/5.812",
	"MagpieRSS/0.72 (+http://magpierss.sf.net; No cache)",
	"Poe-Component-Client-HTTP/0.88",
	"PycURL/7.13.2",
	"PycURL/7.19.0",
	"Python-urllib/2.4",
	"Python-urllib/2.1",
	"SimplePie/1.0 b3.2 (Feed Parser; http://simplepie.org/; Allow like Gecko) Build/20061124",
	"SimplePie/1.1.2 (Feed Parser; http://simplepie.org; Allow like Gecko) Build/20081109150825 ",
	"Snoopy v1.2.1",
	"WWW-Mechanize/1.54",
	"XML-RPC for PHP 2.2.1",
	"Klondike/1.50 (HTTP Win32)",
	"WapTiger/5.0 (http://www.waptiger.com/ ()",
	"WinWAP/4.1 (Win32) WinWAP-X/4.1.0.192",
	"FeedValidator/1.3",
	"HTMLParser/1.6",
	"FPLinkChecker/1.2",
	"REL Link Checker Lite 1.0",
	"W3C-checklink/3.6.2.3 libwww-perl/5.64",
	"W3C-checklink/4.2.1 [4.21] libwww-perl/5.803",
	"Jigsaw/2.2.5 W3C_CSS_Validator_JFouffa/2.0",
	"W3C_Validator/1.432.2.22",
	"W3C_Validator/1.654",
	"CSSCheck/1.2.2",
	"Page Valet/4.1pre5",
	"WDG_Validator/1.6.4",
	"WDG_Validator/1.1",
	"Xenu Link Sleuth 1.2d",
	"Apple-PubSub/65.6",
	"Apple-PubSub/65.1.1",
	"BlogBridge 6.6.2 Discoverer (http://www.blogbridge.com/) 1.6.0_10",
	"BlogBridge 6.6.2 (http://www.blogbridge.com/) 1.6.0_07",
	"Bloglines/3.1 (http://www.bloglines.com)",
	"Dragonfly File Reader",
	"CPG Dragonfly RSS Module Feed Viewer",
	"CPG RSS Module File Reader",
	"Feedfetcher-Google; (+http://www.google.com/feedfetcher.html; 1 subscribers; feed-id=6098063775789346370)",
	"Gregarius/0.5.2 (+http://devlog.gregarius.net/docs/ua)",
	"Gregarius/0.6.0 (+http://devlog.gregarius.net/docs/ua)",
	"Liferea/1.4.14 (Linux; en_US.UTF8; http://liferea.sf.net/)",
	"newsbeuter/1.2 (Linux 2.6.18-xen-r12-xm-217; x86_64; http://www.newsbeuter.org/) libcurl/7.19.4 GnuTLS/2.6.6 zlib/1.2.3",
	"HomePage Rss Reader 1.0; (1 subscribers; feed-id=82385)",
	"Bookdog/5.2",
	"Bookdog/5.1.44",
	"boxee (alpha/Darwin 8.7.1 i386 - 0.9.11.5591)",
	"boxee (alpha/Linux 2.6.28-11-generic #40-Ubuntu SMP Fri Apr 3 17:39:41 UTC 2009 x86_64 - 0.9.7.4826M)",
	"boxee (alpha/Darwin 9.5.2 i386 - 0.9.11.5591)",
	"boxee (alpha/Windows XP Professional Service Pack 3, v.5755 build 2600 - 0.9.9.5324)",
	"boxee (alpha/Windows build 7077 - 0.9.7.4825)",
	"FlyCast/1.34 (BlackBerry; 8330/4.5.0.131 Profile/MIDP-2.0 Configuration/CLDC-1.1 VendorID/-1)",
	"FlyCast/1.35 (BlackBerry; 9530/4.7.0.99 Profile/MIDP-2.0 Configuration/CLDC-1.1 VendorID/-1)",
	"FlyCast/1.32 (BlackBerry; 8330/4.3.0.124 Profile/MIDP-2.0 Configuration/CLDC-1.1 VendorID/-1)",
	"GoldenPod 0.8.1 (podcatcher) libwwwperl",
	"gPodder/0.15.2 (+http://gpodder.org/)",
	"Miro/2.0 (http://www.getmiro.com/; Darwin 9.4.0 Power Macintosh)",
	"Miro/2.1-svn (http://www.getmiro.com/; Windows 2000 )",
	"Miro/2.0.3 (http://www.getmiro.com/; Linux 2.6.24-1-686 i686)",
	"Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9) Gecko Miro/2.0.4 (http://www.getmiro.com/)",
	"Miro/2.0.4 (http://www.getmiro.com/; Windows XP )",
	"PHP/5.2.6",
	"PHP/5.2.8",
	"PHP/5.2.8-pl2-gentoo",
	"Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US; rv:1.9pre) Gecko/2008050715 Thunderbird/3.0a1",
	"Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.8.1.14) Gecko/20080505 Thunderbird/2.0.0.14",
	"Mozilla/5.0 (Windows; U; Windows NT 5.1; cs; rv:1.8.1.21) Gecko/20090302 Lightning/0.9 Thunderbird/2.0.0.21",
	"Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US; rv:1.8.1.19) Gecko/20081209 Thunderbird/2.0.0.19",
	"XBMC/9.04-beta1 r19616 (Linux; Ubuntu 9.04; Linux 2.6.28-11-generic; http://www.xbmc.org)",
	"XBMC/9.04-beta1 r19639 (Windows; Windows XP Professional Service Pack 2 build 2600; http://www.xbmc.org)",
	"XBMC/9.04 r19840 (Mac OS X; Darwin 9.6.0; http://www.xbmc.org)",
	"Anonymouse.org",
	"192.comAgent",
	"Accelobot",
	"Mozilla/5.0 (compatible; heritrix/1.12.0 +http://www.accelobot.com)",
	"Accoona-AI-Agent/1.1.1 (crawler at accoona dot com)",
	"Accoona-AI-Agent/1.1.2 (aicrawler at accoonabot dot com)",
	"Acoon-Robot 4.0.0RC2 (http://www.acoon.de)",
	"Acoon-Robot 4.0.1 (http://www.acoon.de)",
	"Acoon-Robot 4.0.2 (http://www.acoon.de)",
	"Acoon-Robot 4.0.2.17 (http://www.acoon.de)",
	"Acorn/Nutch-0.9 (Non-Profit Search Engine; acorn.isara.org; acorn at isara dot org)",
	"www.adressendeutschland.de",
	"AdsBot-Google (+http://www.google.com/adsbot.html)",
	"AdsBot-Google",
	"aipbot/1.0 (aipbot; http://www.aipbot.com; aipbot@aipbot.com)",
	"aipbot/2-beta (aipbot dev; http://aipbot.com; aipbot@aipbot.com)",
	"appie 1.1 (www.walhello.com)",
	"Mozilla/5.0 (compatible; akula/12.0rc-2; +http://k311.fd.cvut.cz/)",
	"Mozilla/5.0 (compatible; akula/k311; +http://k311.fd.cvut.cz/)",
	"http://www.almaden.ibm.com/cs/crawler [fc13]",
	"http://www.almaden.ibm.com/cs/crawler [bc5]",
	"http://www.almaden.ibm.com/cs/crawler",
	"http://www.almaden.ibm.com/cs/crawler [bc6]",
	"http://www.almaden.ibm.com/cs/crawler [bc14]",
	"http://www.almaden.ibm.com/cs/crawler [hc4]",
	"http://www.almaden.ibm.com/cs/crawler [bc12]",
	"http://www.almaden.ibm.com/cs/crawler [bc22]",
	"Amfibibot/0.07 (Amfibi Robot; http://www.amfibi.com; agent@amfibi.com)",
	"ASAHA Search Engine Turkey V.001 (http://www.asaha.com/)",
	"Mozilla/5.0 (compatible; Ask Jeeves/Teoma; +http://about.ask.com/en/docs/about/webmasters.shtml)",
	"Baiduspider+(+http://www.baidu.com/search/spider.htm)",
	"Baiduspider+(+http://www.baidu.jp/spider/)",
	"Mozilla/5.0 (compatible; BecomeBot/2.3; MSIE 6.0 compatible; +http://www.become.com/site_owners.html)",
	"Mozilla/5.0 (compatible; BecomeBot/3.0; MSIE 6.0 compatible; +http://www.become.com/site_owners.html)",
	"Mozilla/5.0 (compatible; BecomeJPBot/2.3; MSIE 6.0 compatible; +http://www.become.co.jp/site_owners.html)",
	"Mozilla/5.0 (compatible; BecomeBot/3.0; +http://www.become.com/site_owners.html)",
	"Bigsearch.ca/Nutch-1.0-dev (Bigsearch.ca Internet Spider; http://www.bigsearch.ca/; info@enhancededge.com)",
	"Bigsearch.ca/Nutch-0.9-dev (Bigsearch.ca Internet Spider; http://www.bigsearch.ca/; info@enhancededge.com)",
	"Blaiz-Bee/2.00.5655 (+http://www.blaiz.net)",
	"Blaiz-Bee/2.00.5622 (+http://www.blaiz.net)",
	"Blaiz-Bee/2.00.8315 (BE Internet Search Engine http://www.rawgrunt.com)",
	"Blaiz-Bee/2.00.6082 (+http://www.blaiz.net)",
	"boitho.com-dc/0.82 ( http://www.boitho.com/dcbot.html )",
	"boitho.com-dc/0.79 ( http://www.boitho.com/dcbot.html )",
	"boitho.com-dc/0.85 ( http://www.boitho.com/dcbot.html )",
	"boitho.com-dc/0.86 ( http://www.boitho.com/dcbot.html )",
	"boitho.com-dc/0.83 ( http://www.boitho.com/dcbot.html )",
	"btbot/0.4 (+http://www.btbot.com/btbot.html)",
	"Mozilla/5.0 (compatible; Butterfly/1.0; +http://labs.topsy.com/butterfly.html) Gecko/2009032608 Firefox/3.0.8",
	"Mozilla/5.0 (compatible; BuzzRankingBot/1.0; +http://www.buzzrankingbot.com/)",
	"CatchBot/1.0; +http://www.catchbot.com",
	"CazoodleBot/0.1 (CazoodleBot Crawler; http://www.cazoodle.com; mqbot@cazoodle.com)",
	"CazoodleBot/Nutch-0.9-dev (CazoodleBot Crawler; http://www.cazoodle.com/cazoodlebot; cazoodlebot@cazoodle.com)",
	"CazoodleBot/Nutch-0.9-dev (CazoodleBot Crawler; http://www.cazoodle.com; mqbot@cazoodle.com)",
	"CazoodleBot/0.0.2 (http://www.cazoodle.com/contact.php; cbot@cazoodle.com)",
	"CazoodleBot/CazoodleBot-0.1 (CazoodleBot Crawler; http://www.cazoodle.com/cazoodlebot; cazoodlebot@cazoodle.com)",
	"Cazoodle/Nutch-0.9-dev (Cazoodle Nutch Crawler; http://www.cazoodle.com; mqbot@cazoodle.com)",
	"CCBot/1.0 (+http://www.commoncrawl.org/bot.html)",
	"ccubee/2008",
	"ccubee/3.2",
	"ccubee/3.5",
	"ccubee/4.0",
	"ccubee/3.5",
	"ccubee/10.0",
	"ccubee/3.7",
	"ccubee/3.3",
	"ccubee/9.0",
	"mozilla/4.0 (compatible; changedetection/1.0 (admin@changedetection.com))",
	"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; http://www.changedetection.com/bot.html )",
	"Mozilla/5.0 (compatible; Charlotte/1.1; http://www.searchme.com/support/)",
	"City4you/1.3 Cesky (+http://www.city4you.pl)",
	"CJB.NET Proxy",
	"Combine/3 http://combine.it.lth.se/",
	"ConveraCrawler/0.9d (+http://www.authoritativeweb.com/crawl)",
	"ConveraMultiMediaCrawler/0.1 (+http://www.authoritativeweb.com/crawl)",
	"ConveraCrawler/0.9e (+http://www.authoritativeweb.com/crawl)",
	"copyright sheriff (+http://www.copyrightsheriff.com/)",
	"Crawllybot/0.1/0.1 (Crawllybot/0.1; http://www.crawlly.com; crawllybot@crawlly.com)",
	"Crawllybot/0.1/0.1 (Crawllybot/0.1; http://www.crawlly.com; crawler@crawlly.com)",
	"Crawllybot/0.1 (Crawllybot; +http://www.crawlly.com; crawler@crawlly.com)",
	"csci_b659/0.13",
	"DataFountains/DMOZ Feature Vector Corpus Creator (http://ivia.ucr.edu/useragents.shtml)",
	"DataFountains/Dmoz Downloader (http://ivia.ucr.edu/useragents.shtml)",
	"DataparkSearch/4.40.1 (+http://www.dataparksearch.org/)",
	"Mozilla/4.0 (compatible; MSIE is not me; DAUMOA/1.0.0; DAUM Web Robot; Daum Communications Corp., Korea)",
	"Mozilla/4.0 (compatible; MSIE is not me; DAUMOA/1.0.1; DAUM Web Robot; Daum Communications Corp., Korea)",
	"Mozilla/4.0 (compatible; MSIE enviable; DAUMOA/1.0.1; DAUM Web Robot; Daum Communications Corp., Korea; +http://ws.daum.net/aboutkr.html)",
	"Mozilla/4.0 (compatible; MSIE enviable; DAUMOA 2.0; DAUM Web Robot; Daum Communications Corp., Korea; +http://ws.daum.net/aboutkr.html)",
	"Mozilla/5.0 (compatible; MSIE or Firefox mutant; not on Windows server; +http://ws.daum.net/aboutWebSearch.html) Daumoa/2.0",
	"Mozilla/5.0 (compatible; DBLBot/1.0; +http://www.dontbuylists.com/)",
	"DealGates Bot/1.1 by Luc Michalski (http://spider.dealgates.com/bot.html)",
	"Mozilla/5.0 (compatible; del.icio.us-thumbnails/1.0; FreeBSD) KHTML/4.3.2 (like Gecko)",
	"del.icio.us-thumbnails/1.0 Mozilla/5.0 (compatible; Konqueror/3.4; FreeBSD) KHTML/3.4.2 (like Gecko)",
	"Mozilla/4.0 (compatible; DepSpid/5.10; +http://about.depspid.net)",
	"Mozilla/4.0 (compatible; DepSpid/5.26; +http://about.depspid.net)",
	"depspid - the dependency spider",
	"Mozilla/4.0 (compatible; DepSpid/5.07; +http://about.depspid.net)",
	"Mozilla/4.0 (compatible; DepSpid/5.24; +http://about.depspid.net)",
	"Mozilla/4.0 (compatible; DepSpid/5.25; +http://about.depspid.net)",
	"dev-spider2.searchpsider.com/1.3b",
	"Mozilla/5.0 (compatible; DotBot/1.1; http://www.dotnetdotcom.org/, crawler@dotnetdotcom.org)",
	"DuckDuckBot/1.0; (+http://duckduckgo.com/duckduckbot.html)",
	"e-SocietyRobot(http://www.yama.info.waseda.ac.jp/~yamana/es/)",
	"Mozilla/5.0 (compatible; EARTHCOM/2.2; +http://enter4u.eu)",
	"Mozilla/5.0 (compatible; EARTHCOM.info/2.03; +http://www.earthcom.info)",
	"EARTHCOM.info/1.99 [www.earthcom.info]",
	"Mozilla/5.0 (compatible; EARTHCOM.info/2.07; +http://www.earthcom.info)",
	"Mozilla/5.0 (compatible; EARTHCOM.info/2.01; http://www.earthcom.info)",
	"Mozilla/5.0 (compatible; EARTHCOM.info/2.05; +http://www.earthcom.info)",
	"EARTHCOM.info/1.98 [www.earthcom.info]",
	"Mozilla/5.0 (compatible; EARTHCOM.info/2.1; +http://www.earthcom.info)",
	"Mozilla/5.0 (compatible; EARTHCOM.info/2.06; +http://www.earthcom.info)",
	"Mozilla/5.0 (compatible; EARTHCOM.info/2.09; +http://www.earthcom.info)",
	"Mozilla/4.0 (compatible; MSIE is not me; EDI/1.6.6; Edacious & Intelligent Web Robot; Daum Communications Corp., Korea)",
	"Mozilla/4.0 (compatible; EDI/1.6.6; Edacious & Intelligent Web Robot; Daum Communications Corp., Korea)",
	"EDI/1.6.5 (Edacious & Intelligent Web Robot, Daum Communications Corp.)",
	"Mozilla/5.0 (compatible; egothor/8.0g; +http://ego.ms.mff.cuni.cz/)",
	"egothor/8.0f (+http://ego.ms.mff.cuni.cz/)",
	"Mozilla/5.0 (compatible; egothor/12.0rc-2; +http://ego.ms.mff.cuni.cz/)",
	"Mozilla/5.0 (compatible; egothor/11.0d; +http://ego.ms.mff.cuni.cz/)",
	"Mozilla/5.0 (compatible; egothor/11.0d; +https://kocour.ms.mff.cuni.cz/ego/)",
	"ejupiter.com",
	"crawler43.ejupiter.com",
	"EnaBot/1.1 (http://www.enaball.com/crawler.html)",
	"EnaBot/1.2 (http://www.enaball.com/crawler.html)",
	"Enterprise_Search/1.00.143;MSSQL (http://www.innerprise.net/es-spider.asp)",
	"envolk/1.7 (+http://www.envolk.com/envolkspiderinfo.php)",
	"envolk/1.7 (+http://www.envolk.com/envolkspiderinfo.html)",
	"envolk/1.7 (+http://www.envolk.com/envolkspider.html)",
	"envolk[ITS]spider/1.6 (+http://www.envolk.com/envolkspider.html)",
	"Eurobot/1.1 (http://eurobot.ayell.eu)",
	"Mozilla/5.0 (compatible; Exabot-Images/3.0; +http://www.exabot.com/go/robot)",
	"Mozilla/5.0 (compatible; Exabot/3.0; +http://www.exabot.com/go/robot)",
	"exactseek.com",
	"facebookexternalhit/1.0 (+http://www.facebook.com/externalhit_uatext.php)",
	"Factbot 1.09",
	"FAST Enterprise Crawler/6.4 (crawler@fast.no)",
	"FAST Enterprise Crawler 6 used by FAST (jim.mosher@fastsearch.com)",
	"FAST Enterprise Crawler 6 used by Virk.dk - udvikling (thomas.bentzen@capgemini.com)",
	"FAST MetaWeb Crawler (helpdesk at fastsearch dot com)",
	"favorstarbot/1.0 (+http://favorstar.com/bot.html)",
	"FeedCatBot/3.0 (+http://www.feedcat.net/)",
	"Feedster Crawler/3.0; Feedster, Inc.",
	"Findexa Crawler (http://www.findexa.no/gulesider/article26548.ece)",
	"findlinks/1.1.3-beta6 (+http://wortschatz.uni-leipzig.de/findlinks/)",
	"findlinks/1.1.2-a4 (+http://wortschatz.uni-leipzig.de/findlinks/)",
	"findlinks/1.0 (+http://wortschatz.uni-leipzig.de/findlinks/)",
	"findlinks/1.1.3-beta1 (+http://wortschatz.uni-leipzig.de/findlinks/)",
	"findlinks/1.0.8 (+http://wortschatz.uni-leipzig.de/findlinks/)",
	"findlinks/1.0.9-a2 (+http://wortschatz.uni-leipzig.de/findlinks/)",
	"findlinks/1.0.9 (+http://wortschatz.uni-leipzig.de/findlinks/)",
	"findlinks/1.1.3-beta2 (+http://wortschatz.uni-leipzig.de/findlinks/)",
	"findlinks/1.1.2-a5 (+http://wortschatz.uni-leipzig.de/findlinks/)",
	"findlinks/1.1.1-a2 (+http://wortschatz.uni-leipzig.de/findlinks/)",
	"findlinks/1.1.1 (+http://wortschatz.uni-leipzig.de/findlinks/)",
	"findlinks/1.1.2-a3 (+http://wortschatz.uni-leipzig.de/findlinks/)",
	"findlinks/0.976 (+http://wortschatz.uni-leipzig.de/findlinks/)",
	"findlinks/1.1.3-beta7 (+http://wortschatz.uni-leipzig.de/findlinks/)",
	"findlinks/1.1.2-a2 (+http://wortschatz.uni-leipzig.de/findlinks/)",
	"findlinks/1.1.3-beta4 (+http://wortschatz.uni-leipzig.de/findlinks/)",
	"findlinks/0.975 (+http://wortschatz.uni-leipzig.de/findlinks/)",
	"findlinks/0.973 (+http://wortschatz.uni-leipzig.de/findlinks/)",
	"findlinks/1.1.3-beta8 (+http://wortschatz.uni-leipzig.de/findlinks/)",
	"findlinks/0.971 (+http://wortschatz.uni-leipzig.de/findlinks/)",
	"findlinks/1.01 (+http://wortschatz.uni-leipzig.de/findlinks/)",
	"findlinks/1.1.3-beta9 (+http://wortschatz.uni-leipzig.de/findlinks/)",
	"findlinks/1.1.1-a5 (+http://wortschatz.uni-leipzig.de/findlinks/)",
	"findlinks/1.1.4-beta1 (+http://wortschatz.uni-leipzig.de/findlinks/)",
	"findlinks/1.1-a9 (+http://wortschatz.uni-leipzig.de/findlinks/)",
	"findlinks/1.1 (+http://wortschatz.uni-leipzig.de/findlinks/)",
	"findlinks/0.966 (+http://wortschatz.uni-leipzig.de/findlinks/)",
	"findlinks/1.1.1-a1 (+http://wortschatz.uni-leipzig.de/findlinks/)",
	"findlinks/1.1-a7 (+http://wortschatz.uni-leipzig.de/findlinks/)",
	"findlinks/1.1-a8 (+http://wortschatz.uni-leipzig.de/findlinks/)",
	"findlinks/1.1-a5 (+http://wortschatz.uni-leipzig.de/findlinks/)",
	"findlinks/1.1-a4 (+http://wortschatz.uni-leipzig.de/findlinks/)",
	"flatlandbot/baypup (Flatland Industries Web Spider; http://www.flatlandindustries.com/flatlandbot; jason@flatlandindustries.com)",
	"great-plains-web-spider/flatlandbot (Flatland Industries Web Robot; http://www.flatlandindustries.com/flatlandbot.php; jason@flatlandindustries.com)",
	"great-plains-web-spider/gpws (Flatland Industries Web Spider; http://www.flatlandindustries.com/flatlandbot.php; jason@flatlandindustries.com)",
	"flatlandbot/flatlandbot (Flatland Industries Web Spider; http://www.flatlandindustries.com/flatlandbot.php; jason@flatlandindustries.com)",
	"great-plains-web-spider/flatlandbot (Flatland Industries Web Spider; http://www.flatlandindustries.com/flatlandbot.php; jason@flatlandindustries.com)",
	"Forschungsportal/0.8-dev (Testinstallation; http://www.forschungsportal.net/; fpcrawler@rrzn.uni-hannover.de)",
	"Francis/2.0 (francis@neomo.de http://www.neomo.de/pages/crawler.php)",
	"Mozilla/5.0 (compatible; FunnelBack; http://cyan.funnelback.com/robot.html)",
	"Mozilla/4.0 compatible FurlBot/Furl Search 2.0 (FurlBot; http://www.furl.net; wn.furlbot@looksmart.net)",
	"FyberSpider/1.2 (http://www.fybersearch.com/fyberspider.php)",
	"g2Crawler (nobody@airmail.net)",
	"Gaisbot/3.0+(robot06@gais.cs.ccu.edu.tw;+http://gais.cs.ccu.edu.tw/robot.php)",
	"Gaisbot/3.0+(robot@gais.cs.ccu.edu.tw;+http://gais.cs.ccu.edu.tw/robot.php)",
	"Gallent Search Spider v1.4 Robot 3 (http://www.GallentSearch.com/robot)",
	"genieBot (wgao@genieknows.com)",
	"genieBot ((http://64.5.245.11/faq/faq.html))",
	"GeonaBot/1.2; http://www.geona.com/",
	"Giant/1.0 (Openmaru bot; robot@openmaru.com)",
	"Gigabot/3.0 (http://www.gigablast.com/spider.html)",
	"GingerCrawler/1.0 (Language Assistant for Dyslexics; www.gingersoftware.com/crawler_agent.htm; support at ginger software dot com)",
	"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.2; SV1; .NET CLR 1.1.4322; Girafabot [girafa.com])",
	"Mozilla/4.0 (compatible; MSIE 5.0; Windows NT; Girafabot; girafabot at girafa dot com; http://www.girafa.com)",
	"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 4.0; Girafabot; girafabot at girafa dot com; http://www.girafa.com)",
	"GOFORITBOT ( http://www.goforit.com/about/ )",
	"Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)",
	"Googlebot-Image/1.0",
	"Feedfetcher-Google; (+http://www.google.com/feedfetcher.html; feed-id=9447642013063130247)",
	"Mediapartners-Google",
	"GurujiBot/1.0 (+http://www.guruji.com/en/WebmasterFAQ.html)",
	"Mozilla/5.0 GurujiBot/1.0 ( http://www.guruji.com/en/WebmasterFAQ.html)",
	"GurujiBot/1.0 (+http://www.guruji.com/WebmasterFAQ.html)",
	"HatenaScreenshot/1.0 (checker)",
	"HiddenMarket-1.0-beta (www.hiddenmarket.net/crawler.php)",
	"holmes/3.11 (OnetSzukaj/5.0; +http://szukaj.onet.pl)",
	"holmes/3.12.4 (http://morfeo.centrum.cz/bot)",
	"holmes/3.9 (OnetSzukaj/5.0; +http://szukaj.onet.pl)",
	"holmes/3.10.1 (OnetSzukaj/5.0; +http://szukaj.onet.pl)",
	"holmes/3.9 (onet.pl)",
	"holmes/3.11 (http://morfeo.centrum.cz/bot)",
	"HooWWWer/2.1.3 (debugging run) (+http://cosco.hiit.fi/search/hoowwwer/ | mailto:crawler-infohiit.fi)",
	"HooWWWer/2.2.0 (debugging run) (+http://cosco.hiit.fi/search/hoowwwer/ | mailto:crawler-infohiit.fi)",
	"cinetic_htdig",
	"HTML2JPG Enterprise, http://www.html2jpg.com",
	"iaskspider/2.0(+http://iask.com/help/help_index.html)",
	"ia_archiver (+http://www.alexa.com/site/help/webmasters; crawler@alexa.com)",
	"ia_archiver-web.archive.org",
	"ICC-Crawler(Mozilla-compatible; http://kc.nict.go.jp/icc/crawl.html; icc-crawl-contact(at)ml(dot)nict(dot)go(dot)jp)",
	"ICC-Crawler(Mozilla-compatible; http://kc.nict.go.jp/icc/crawl.html; icc-crawl(at)ml(dot)nict(dot)go(dot)jp)",
	"ICF_Site_Crawler+(see+http://www.infocenter.fi/spiderinfo.html)",
	"ichiro/2.01 (http://help.goo.ne.jp/door/crawler.html)",
	"ichiro/2.0 (ichiro@nttr.co.jp)",
	"ichiro/3.0 (http://help.goo.ne.jp/door/crawler.html)",
	"ichiro/1.0 (ichiro@nttr.co.jp)",
	"ichiro/2.0 (http://help.goo.ne.jp/door/crawler.html)",
	"ilial/Nutch-0.9 (Ilial, Inc. is a Los Angeles based Internet startup company.; http://www.ilial.com/crawler; crawl@ilial.com)",
	"ilial/Nutch-0.9 (Ilial, Inc. is a Los Angeles based Internet startup company. For more information please visit http://www.ilial.com/crawler; http://www.ilial.com/crawler; crawl@ilial.com)",
	"ilial/Nutch-0.9-dev",
	"IlseBot/1.1",
	"IlTrovatore/1.2 (IlTrovatore; http://www.iltrovatore.it/bot.html; bot@iltrovatore.it)",
	"IlTrovatore-Setaccio/1.2 (Italy search engine; http://www.iltrovatore.it/bot.html; bot@iltrovatore.it)",
	"IlTrovatore-Setaccio/1.2 (It search engine; http://www.iltrovatore.it/bot.html; bot@iltrovatore.it)",
	"InfociousBot (+http://corp.infocious.com/tech_crawler.php)",
	"Intelix/0.8 (cs; http://www.microton.cz/intelix/; microton@@microton.cz)",
	"Intelix/0.7 (cs; http://www.microton.cz/intelix/; microton@@microton.cz)",
	"InternetSeer.com",
	"Ipselonbot/1.0-beta (+; http://www.ipselon.com/intl/en/ipselonbot.html)",
	"Ipselonbot/0.47-beta (Ipselon; http://www.ipselon.com/intl/en/ipselonbot.html; ipselonbot@ipselon.com)",
	"IRLbot/2.0 (compatible; MSIE 6.0; http://irl.cs.tamu.edu/crawler)",
	"IRLbot/3.0 (compatible; MSIE 6.0; http://irl.cs.tamu.edu/crawler)",
	"IRLbot/3.0 (compatible; MSIE 6.0; http://irl.cs.tamu.edu/crawler/)",
	"IRLbot/2.0 (+http://irl.cs.tamu.edu/crawler)",
	"JadynAve - http://www.jadynave.com/robot",
	"Jambot/0.1.1 (Jambot; http://www.jambot.com/blog; crawler@jambot.com)",
	"JyxobotRSS/0.06",
	"Jyxobot/1",
	"kakle-spider/0.1 (kakle-spider; http://www.kakle.com/bot.html; support@kakle.com)",
	"kalooga/KaloogaBot (Kalooga; http://www.kalooga.com/info.html?page=crawler)",
	"kalooga/KaloogaBot (Kalooga; http://www.kalooga.com/info.html?page=crawler; crawler@kalooga.com)",
	"KeywenBot/4.1 http://www.keywen.com/Encyclopedia/Links",
	"Kongulo v0.1 personal web crawler",
	"KRetrieve/1.1/dbsearchexpert.com",
	"Krugle/Krugle,Nutch/0.8+ (Krugle web crawler; http://corp.krugle.com/crawler/info.html; webcrawler@krugle.com)",
	"Krugle/Krugle,Nutch/0.8+ (Krugle web crawler; http://www.krugle.com/crawler/info.html; webcrawler@krugle.com)",
	"ksibot/7.0d (+http://ego.ms.mff.cuni.cz/)",
	"ksibot/8.0a (+http://ego.ms.mff.cuni.cz/)",
	"ksibot/5.2m (+http://ego.ms.mff.cuni.cz/)",
	"LapozzBot/1.4 (+http://robot.lapozz.com)",
	"LapozzBot/1.4 (+http://robot.lapozz.hu)",
	"Larbin (larbin2.6.3@unspecified.mail)",
	"LarbinWebCrawler (spider@download11.com)",
	"LinguaBot/v0.001-dev (MultiLinual Sarch Engine v0.001; LinguaSeek; admin at linguaseek dot com)",
	"Link Valet Online 1.2",
	"Link Valet Online 1.1",
	"Mozilla/5.0 (compatible; LinksManager.com_bot +http://linksmanager.com/linkchecker.html)",
	"LinkWalker/2.0",
	"LinkWalker",
	"lmspider (lmspider@scansoft.com)",
	"lmspider/Nutch-0.9-dev (For research purposes.; www.nuance.com)",
	"magpie-crawler/1.1 Linux amd64 null (http://www.magpie.net)",
	"Mahiti.Com/Mahiti Crawler-1.0 (Mahiti.Com; http://mahiti.com ; mahiti.com)",
	"Mail.Ru/1.0",
	"Megatext/Megatext-0.5 (beta; http://www.megatext.cz/; microton@microton.cz)",
	"Megatext/Nutch-0.8.1 (Beta; http://www.megatext.cz/; microton@microton.cz)",
	"Metaspinner/0.01 (Metaspinner; http://www.meta-spinner.de/; support@meta-spinner.de/)",
	"MetaTagRobot/1.6 (http://www.widexl.com/remote/search-engines/metatag-analyzer.html)",
	"MetaTagRobot/2.1 (http://www.widexl.com/remote/search-engines/metatag-analyzer.html)",
	"miniRank/1.2 (miniRank; http://minirank.com/; MiniRank)",
	"miniRank/3.1 (miniRank; www.minirank.com; website ranking engine)",
	"miniRank/2.0 (miniRank; http://minirank.com/; website ranking engine)",
	"miniRank/1.6 (Website ranking; www.minirank.com; robot)",
	"miniRank/1.5 (miniRank; www.minirank.com; robot)",
	"Mozilla/5.0 (compatible; MJ12bot/v1.2.4; http://www.majestic12.co.uk/bot.php?+)",
	"MLBot (www.metadatalabs.com/mlbot)",
	"MLBot (www.metadatalabs.com)",
	"MnoGoSearch/3.3.6",
	"MnoGoSearch/3.3.2",
	"Motoricerca-Robots.txt-Checker/1.0 (http://tool.motoricerca.info/robots-checker.phtml)",
	"Mozdex/0.7.2-dev (Mozdex; http://www.mozdex.com/bot.html; spider@mozdex.com)",
	"Mozdex/0.7.1 (Mozdex; http://www.mozdex.com/bot.html; spider@mozdex.com)",
	"Mozdex/0.7.2 (Mozdex; http://www.mozdex.com/bot.html; spider@mozdex.com)",
	"Mozilla/5.0 (compatible; Mp3Bot/0.4; +http://mp3realm.org/mp3bot/)",
	"MQBOT/Nutch-0.9-dev (MQBOT Crawler; http://falcon.cs.uiuc.edu; mqbot@cs.uiuc.edu)",
	"MQBOT/Nutch-0.9-dev (MQBOT Nutch Crawler; http://falcon.cs.uiuc.edu; mqbot@cs.uiuc.edu)",
	"MQbot metaquerier.cs.uiuc.edu/crawler",
	"MQBOT/Nutch-0.9-dev (MQBOT Nutch Crawler; http://vwbot.cs.uiuc.edu; mqbot@cs.uiuc.edu)",
	"msnbot/1.1 (+http://search.msn.com/msnbot.htm)",
	"msnbot-media/1.1 (+http://search.msn.com/msnbot.htm)",
	"msnbot/1.0 (+http://search.msn.com/msnbot.htm)",
	"msnbot/2.0b (+http://search.msn.com/msnbot.htm)",
	"MSRBOT (http://research.microsoft.com/research/sv/msrbot/)",
	"MSRBOT (http://research.microsoft.com/research/sv/msrbot/",
	"MSRBOT",
	"MSRBOT (http://research.microsoft.com/research/sv/msrbot)",
	"multicrawler (+http://sw.deri.org/2006/04/multicrawler/robots.html)",
	"mozilla/4.0 (compatible; myfamilybot/1.0; http://www.ancestry.com/learn/bot.aspx)",
	"Mozilla/4.0 (compatible; MyFamilyBot/1.0; http://www.ancestry.com/learn/bot.aspx)",
	"Mozilla/4.0 (compatible; MyFamilyBot/1.0; http://www.myfamilyinc.com)",
	"NaverBot-1.0 (NHN Corp. / +82-31-784-1989 / nhnbot@naver.com)",
	"Mozilla/4.0 (compatible; NaverBot/1.0; nhnbot@naver.com)",
	"NaverBot-1.0 (NHN Corp. / +82-2-3011-1989 / nhnbot@naver.com)",
	"Mozilla/4.0 (compatible; NaverBot/1.0; http://help.naver.com/delete_main.asp)",
	"Mozilla/4.0 (compatible; NaverBot/1.0; http://help.naver.com/customer_webtxt_02.jsp)",
	"navissobot/1.7 (+http://navisso.com/)",
	"nestReader/0.2 (discovery; http://echonest.com/reader.shtml; reader at echonest.com)",
	"Netintelligence LiveAssessment - www.netintelligence.com",
	"NetResearchServer/3.5(loopimprovements.com/robot.html)",
	"nrsbot/5.0(loopimprovements.com/robot.html)",
	"NetResearchServer/4.0(loopimprovements.com/robot.html)",
	"nrsbot/5.0(loopip.com/robot.html)",
	"NetWhatCrawler/0.06-dev (NetWhatCrawler from NetWhat.com; http://www.netwhat.com; support@netwhat.com)",
	"NextGenSearchBot 1 (for information visit http://www.zoominfo.com/About/misc/NextGenSearchBot.aspx)",
	"NextGenSearchBot 1 (for information visit http://about.zoominfo.com/About/NextGenSearchBot.aspx)",
	"Mozilla/5.0 (compatible; nextthing.org/1.0; +http://www.nextthing.org/bot)",
	"NG/2.0",
	"NG-Search/0.90 (NG-SearchBot; http://www.ng-search.com; )",
	"NG-Search/0.9.8 (NG-SearchBot; http://www.ng-search.com)",
	"Mozilla/5.0 (Windows;) NimbleCrawler 1.14 obeys UserAgent NimbleCrawler For problems contact: crawler@healthline.com",
	"Mozilla/5.0 (Windows;) NimbleCrawler 2.0.0 obeys UserAgent NimbleCrawler For problems contact: crawler@healthline.com",
	"Mozilla/5.0 (Windows;) NimbleCrawler 1.15 obeys UserAgent NimbleCrawler For problems contact: crawler@healthline.com",
	"Mozilla/5.0 (Windows; U; Windows NT 5.0; en-US; rv:1.7.7) NimbleCrawler 1.11 obeys UserAgent NimbleCrawler For problems contact: crawler_at_dataalchemy.com",
	"Mozilla/5.0 (Windows;) NimbleCrawler 1.12 obeys UserAgent NimbleCrawler For problems contact: crawler@healthline.com",
	"Mozilla/5.0 (Windows;) NimbleCrawler 2.0.1 obeys UserAgent NimbleCrawler For problems contact: crawler@healthline.com",
	"Mozilla/5.0 (Windows;) NimbleCrawler 1.13 obeys UserAgent NimbleCrawler For problems contact: crawler@healthline.com",
	"Mozilla/5.0 (Windows;) NimbleCrawler 2.0.2 obeys UserAgent NimbleCrawler For problems contact: crawler@healthline.com",
	"noyona_0_1",
	"NPBot/3 (NPBot; http://www.nameprotect.com; npbot@nameprotect.com)",
	"Nusearch Spider (www.nusearch.com)",
	"NuSearch Spider (compatible; MSIE 6.0)",
	"NutchCVS/Nutch-0.9 (Nutch; http://lucene.apache.org/nutch/bot.html; nutch-agent@lucene.apache.org)",
	"InternetArchive/0.8-dev (Nutch; http://lucene.apache.org/nutch/bot.html; nutch-agent@lucene.apache.org)",
	"NutchCVS/0.06-dev (http://www.nutch.org/docs/en/bot.html; rhwarren+nutch@uwaterloo.ca)",
	"NutchCVS/0.8-dev (Nutch; http://lucene.apache.org/nutch/bot.html; nutch-agent@lucene.apache.org)",
	"NutchCVS/0.8-dev (Nutch running at UW; http://www.nutch.org/docs/en/bot.html; sycrawl@cs.washington.edu)",
	"NutchCVS/0.06-dev (Nutch; http://www.nutch.org/docs/en/bot.html; nutch-agent@lists.sourceforge.net)",
	"HouxouCrawler/Nutch-0.9 (houxou.com's nutch-based crawler which serves special interest on-line communities; http://www.houxou.com/crawler; crawler at houxou dot com)",
	"NutchCVS/0.7.1 (Nutch running at UW; http://www.nutch.org/docs/en/bot.html; sycrawl@cs.washington.edu)",
	"NutchCVS/0.7.2 (Nutch; http://lucene.apache.org/nutch/bot.html; nutch-agent@lucene.apache.org)",
	"NutchCVS/0.7.1 (Nutch; http://lucene.apache.org/nutch/bot.html; nutch-agent@lucene.apache.org)",
	"NutchCVS/0.7.1 (Nutch; http://www.vvdb.org; voorzitter@vvdb.org)",
	"NutchCVS/0.7.1 (Nutch running at UW; http://crawlers.cs.washington.edu/; sycrawl@cs.washington.edu)",
	"NutchCVS/0.7.1 (Nutch; http://lucene.apache.org/nutch/bot.html; raphael@unterreuth.de)",
	"HouxouCrawler/Nutch-0.8 (houxou.com's nutch-based crawler which serves special interest on-line communities; http://www.houxou.com/crawler; crawler at houxou dot com)",
	"HouxouCrawler/Nutch-0.8.2-dev (houxou.com's nutch-based crawler which serves special interest on-line communities; http://www.houxou.com/crawler; crawler at houxou dot com)",
	"HouxouCrawler/Nutch-0.9-dev (houxou.com's nutch-based crawler which serves special interest on-line communities; http://www.houxou.com/crawler; crawler at houxou dot com)",
	"asked/Nutch-0.8 (web crawler; http://asked.jp; epicurus at gmail dot com)",
	"heeii/Nutch-0.9-dev (heeii.com; www.heeii.com; nutch at heeii.com)",
	"BilgiBetaBot/0.8-dev (bilgi.com (Beta) ; http://lucene.apache.org/nutch/bot.html; nutch-agent@lucene.apache.org)",
	"NutchOSU-VLIB/0.7 (Nutch; http://lucene.apache.org/nutch/bot.html; nutch-agent@lucene.apache.org)",
	"NutchCVS/0.7 (Nutch; http://lucene.apache.org/nutch/bot.html; nutch-agent@lucene.apache.org)",
	"ObjectsSearch/0.2 (ObjectsSearch; http://www.ObjectsSearch.com/bot.html; support@thesoftwareobjects.com)",
	"ObjectsSearch/0.07 (ObjectsSearch; http://www.ObjectsSearch.com/bot.html; support@thesoftwareobjects.com)",
	"oBot",
	"Mozilla/4.0 (compatible; MSIE 5.5; Windows NT 4.0; obot)",
	"OmniExplorer_Bot/4.06 (+http://www.omni-explorer.com) WorldIndexer",
	"OmniExplorer_Bot/4.02 (+http://www.omni-explorer.com) WorldIndexer",
	"OmniExplorer_Bot/6.47 (+http://www.omni-explorer.com) WorldIndexer",
	"Mozilla/5.0 (compatible; OnetSzukaj/5.0; +http://szukaj.onet.pl)",
	"Mozilla/5.0 (compatible; OnetSzukaj/5.0; +http://szukaj.onet.pl",
	"OOZBOT/0.20 ( -- ; http://www.setooz.com/oozbot.html ; agentname at setooz dot_com )",
	"OOZBOT/0.20 ( Setooz vÃ½raznÃ½ ako say-th-uuz, znamenÃ¡ mosty. ; http://www.setooz.com/oozbot.html ; agentname at setooz dot_com )",
	"Openfind data gatherer, Openbot/3.0+(robot-response@openfind.com.tw;+http://www.openfind.com.tw/robot.html)",
	"Orbiter (+http://www.dailyorbit.com/bot.htm)",
	"Mozilla/5.0 (compatible; OsO; http://oso.octopodus.com/abot.html)",
	"owsBot/0.1 (Nutch; www.oneworldstreet.com; nutch-agent@lucene.apache.org)",
	"owsBot/0.2 (owsBot; www.oneworldstreet.com; owsBot)",
	"ozelot/2.7.3 (Search engine indexer; www.flying-cat.de/ozelot; ozelot@flying-cat.de)",
	"PageBitesHyperBot/600 (http://www.pagebites.com/)",
	"Pagebull http://www.pagebull.com/",
	"page_verifier (http://www.securecomputing.com/goto/pv)",
	"panscient.com",
	"Pingdom GIGRIB (http://www.pingdom.com)",
	"Mozilla/5.0 (compatible; Pogodak.co.yu/3.1)",
	"Mozilla/5.0 (compatible; polixea.de-Robot +http://www.polixea.de)",
	"Pompos/1.3 http://dir.com/pompos.html",
	"posterus (seek.se) +http://www.seek.se/studio/index.php?id=47&t=details",
	"psbot/0.1 (+http://www.picsearch.com/bot.html)",
	"Mozilla/5.0 (compatible; Quantcastbot/1.0; www.quantcast.com)",
	"RAMPyBot - www.giveRAMP.com/0.1 (RAMPyBot - www.giveRAMP.com; http://www.giveramp.com/bot.html; support@giveRAMP.com)",
	"RAMPyBot - www.giveRAMP.com/1.0 (RAMPyBot - www.giveRAMP.com; http://www.giveramp.com/bot.html; support@giveRAMP.com)",
	"RedBot/redbot-1.0 (Rediff.com Crawler; redbot at rediff dot com)",
	"Robo Crawler 6.4.5 (robocrawler@bb.softbank.co.jp)",
	"RSSMicro.com RSS/Atom Feed Robot",
	"SBIder/0.7 (SBIder; http://www.sitesell.com/sbider.html; http://support.sitesell.com/contact-support.html)",
	"SBIder/SBIder-0.8.2-dev (http://www.sitesell.com/sbider.html)",
	"SBIder/0.8-dev (SBIder; http://www.sitesell.com/sbider.html; http://support.sitesell.com/contact-support.html)",
	"schibstedsokbot (compatible; Mozilla/5.0; MSIE 5.0; FAST FreshCrawler 6; +http://www.schibstedsok.no/bot/)",
	"Mozilla/3.0 (compatible; ScollSpider; http://www.webwobot.com)",
	"Scooter/3.3",
	"Mozilla/5.0 (compatible; ScoutJet; +http://www.scoutjet.com/)",
	"Search Engine World Robots.txt Validator at http://www.searchengineworld.com/cgi-bin/robotcheck.cgi",
	"Seekbot/1.0 (http://www.seekbot.net/bot.html) RobotsTxtFetcher/1.2",
	"Sensis Web Crawler (search_comments\at\sensis\dot\com\dot\au)",
	"Sensis Web Crawler (search_comments\at\sensis\dot\com\dot\au)",
	"Mozilla/5.0 (compatible; SEO browser; http://seo-browser.net/faq",
	"Mozilla/5.0 (compatible; SEO browser; http://seo-browser.net/faq#ua)",
	"CloakDetect/0.9 (+http://fulltext.seznam.cz/)",
	"SeznamBot/2.0-Test (+http://fulltext.sblog.cz/robot/)",
	"Mozilla/5.0 (compatible; Seznam screenshot-generator 2.0; +http://fulltext.sblog.cz/screenshot/)",
	"SeznamBot/2.0 (+http://fulltext.sblog.cz/robot/)",
	"Shelob (shelob@gmx.net)",
	"Shim-Crawler(Mozilla-compatible; http://www.logos.ic.i.u-tokyo.ac.jp/crawl/; crawl@logos.ic.i.u-tokyo.ac.jp)",
	"Shim-Crawler(Mozilla-compatible; http://www.logos.ic.i.u-tokyo.ac.jp/crawler/; crawl@logos.ic.i.u-tokyo.ac.jp)",
	"ShopWiki/1.0 ( +http://www.shopwiki.com/wiki/Help:Bot)",
	"Silk/1.0",
	"silk/1.0 (+http://www.slider.com/silk.htm)/3.7",
	"Sirketcebot/v.01 (http://www.sirketce.com/bot.html)",
	"Busiversebot/v1.0 (http://www.busiverse.com/bot.php)",
	"Mozilla/5.0 (compatible; SkreemRBot +http://skreemr.com)",
	"snap.com beta crawler v0",
	"Snapbot/1.0 (Snap Shots, +http://www.snap.com)",
	"Snapbot/1.0 (+http://www.snap.com)",
	"Snapbot/1.0",
	"Mozilla/5.0 (compatible; SnapPreviewBot; en-US; rv:1.8.0.9) Gecko/20061206 Firefox/1.5.0.9",
	"Snapbot/1.0 (Site Search Crawler, +http://www.snap.com)",
	"Snappy/1.1 ( http://www.urltrends.com/ )",
	"SniffRSS/0.5beta (+http://www.blogator.com/)",
	"Sogou web spider/4.0(+http://www.sogou.com/docs/help/webmasters.htm#07)",
	"Sogou develop spider/4.0(+http://www.sogou.com/docs/help/webmasters.htm#07)",
	"sogou web spider(+http://www.sogou.com/docs/help/webmasters.htm#07)",
	"sogou spider",
	"Sogou web spider/3.0(+http://www.sogou.com/docs/help/webmasters.htm#07)",
	"sogou web spider http://www.sogou.com/docs/help/webmasters.htm#07",
	"sohu-search",
	"Speedy Spider (http://www.entireweb.com/about/search_tech/speedyspider/)",
	"Speedy Spider (http://www.entireweb.com/about/search_tech/speedy_spider/)",
	"Speedy Spider (Entireweb; Beta/1.1; http://www.entireweb.com/about/search_tech/speedyspider/)",
	"Speedy Spider (Entireweb; Beta/1.3; http://www.entireweb.com/about/search_tech/speedyspider/)",
	"Speedy Spider (Entireweb; Beta/1.2; http://www.entireweb.com/about/search_tech/speedyspider/)",
	"Speedy Spider (Entireweb; Beta/1.0; http://www.entireweb.com/about/search_tech/speedyspider/)",
	"Spock Crawler (http://www.spock.com/crawler)",
	"SpokeSpider/1.0 (http://support.spoke.com/webspider/) Mozilla/5.0 (not really)",
	"sproose/0.1-alpha (sproose crawler; http://www.sproose.com/bot.html; crawler@sproose.com)",
	"sproose/1.0beta (sproose bot; http://www.sproose.com/bot.html; crawler@sproose.com)",
	"sproose/0.1 (sproose bot; http://www.sproose.com/bot.html; crawler@sproose.com)",
	"SrevBot/2.0 (SrevBot; http://winsrev.com/bot.html; bot@winsrev.com)",
	"SrevBot/1.2 (SrevBot; http://winsrev.com/bot.html; bot@winsrev.comg)",
	"StackRambler/2.0 (MSIE incompatible)",
	"Steeler/3.2 (http://www.tkl.iis.u-tokyo.ac.jp/~crawler/)",
	"Steeler/3.3 (http://www.tkl.iis.u-tokyo.ac.jp/~crawler/)",
	"SurveyBot/2.3 (Whois Source)",
	"SygolBot http://www.sygol.com",
	"SynooBot/0.7.1 (SynooBot; http://www.synoo.de/bot.html; webmaster@synoo.com)",
	"SynooBot (compatible; Synoobot/0.7.1; http://www.synoo.com/search/bot.html)",
	"Szukacz/1.5 (robot; www.szukacz.pl/html/jak_dziala_robot.html; info@szukacz.pl)",
	"Szukacz/1.5 (robot; www.szukacz.pl/jakdzialarobot.html; info@szukacz.pl)",
	"Szukankobot /1.0 (+http://www.szukanko.pl/addurl.php)",
	"Teemer (NetSeer, Inc.; http://www.netseer.com/crawler.html; crawler@netseer.com)",
	"Teemer (NetSeer, Inc. is a Los Angeles based Internet startup company.; http://www.netseer.com/crawler.html; crawler@netseer.com)",
	"Mozilla/2.0 (compatible; Ask Jeeves/Teoma; +http://sp.ask.com/docs/about/tech_crawling.html)",
	"Mozilla/2.0 (compatible; Ask Jeeves/Teoma; http://about.ask.com/en/docs/about/webmasters.shtml)",
	"Mozilla/2.0 (compatible; Ask Jeeves/Teoma)",
	"Mozilla/2.0 (compatible; Ask Jeeves/Teoma; +http://about.ask.com/en/docs/about/webmasters.shtml)",
	"TeragramCrawler",
	"textractor.harvester/h7/1.0 (+http://ufal.mff.cuni.cz/project/textractor/, textractor@ufal.mff.cuni.cz)",
	"textractor.harvester/h3/1.0 (+http://ufal.mff.cuni.cz/project/textractor/, textractor@ufal.mff.cuni.cz)",
	"textractor.queuekeeper/0.1 (+http://ufal.mff.cuni.cz/project/textractor/, textractor@ufal.mff.cuni.cz)",
	"textractor.harvester/h24/1.0 (+http://ufal.mff.cuni.cz/project/textractor/, textractor@ufal.mff.cuni.cz)",
	"textractor.harvester/h27/1.0 (+http://ufal.mff.cuni.cz/project/textractor/, textractor@ufal.mff.cuni.cz)",
	"textractor.harvester/h2/1.0 (+http://ufal.mff.cuni.cz/project/textractor/, textractor@ufal.mff.cuni.cz)",
	"textractor.harvester/h39/1.0 (+http://ufal.mff.cuni.cz/project/textractor/, textractor@ufal.mff.cuni.cz)",
	"textractor.harvester/h37/1.0 (+http://ufal.mff.cuni.cz/project/textractor/, textractor@ufal.mff.cuni.cz)",
	"textractor.harvester/h38/1.0 (+http://ufal.mff.cuni.cz/project/textractor/, textractor@ufal.mff.cuni.cz)",
	"textractor.harvester/h5/1.0 (+http://ufal.mff.cuni.cz/project/textractor/, textractor@ufal.mff.cuni.cz)",
	"textractor.harvester/h12/1.0 (+http://ufal.mff.cuni.cz/project/textractor/, textractor@ufal.mff.cuni.cz)",
	"textractor.harvester/h34/1.0 (+http://ufal.mff.cuni.cz/project/textractor/, textractor@ufal.mff.cuni.cz)",
	"Mozilla/5.0 (compatible; Theophrastus/2.0; +http://users.cs.cf.ac.uk/N.A.Smith/theophrastus.php)",
	"thumbshots-de-Bot (Version: 1.02, powered by www.thumbshots.de)",
	"Touche (+http://www.touche.com.ve)",
	"TurnitinBot/2.1 (http://www.turnitin.com/robot/crawlerinfo.html)",
	"TurnitinBot/2.0 (http://www.turnitin.com/robot/crawlerinfo.html)",
	"TutorGigBot/1.5 ( +http://www.tutorgig.info )",
	"Mozilla/5.0 (Twiceler-0.9 http://www.cuil.com/twiceler/robot.html)",
	"unido-bot",
	"updated/0.1-beta (updated; http://www.updated.com; crawler@updated.com)",
	"updated/0.1-alpha (updated crawler; http://www.updated.com; crawler@updated.com)",
	"urlfan-bot/1.0; +http://www.urlfan.com/site/bot/350.html",
	"Vagabondo/3.0 (webagent at wise-guys dot nl)",
	"VERASYS 2k Mozilla/4.0 (compatible; en) (compatible; MSIE 6.0; Windows NT 5.2; (+ http://web.verasys.ro); SV1; Unix; .NET CLR 1.1.4322)",
	"Verifactrola/1.0",
	"Mozilla/5.0 (compatible; Vermut +http://vermut.aol.com)",
	"Vespa Crawler",
	"virus_detector (virus_harvester@securecomputing.com)",
	"Visbot/1.1 (Visvo.com - The Category Search Engine!; http://www.visvo.com/bot.html; bot@visvo.com)",
	"VisBot/2.0 (Visvo.com Crawler; http://www.visvo.com/bot.html; bot@visvo.com)",
	"VMBot/0.9 (VMBot; http://www.verticalmatch.com; vmbot@tradedot.com)",
	"VMBot/0.7.2 (VMBot; http://www.VerticalMatch.com/; vmbot@tradedot.com)",
	"void-bot/0.1 (bot@void.be; http://www.void.be/)",
	"Mozilla/4.0 (compatible; MSIE 5.0; Windows 95) VoilaBot BETA 1.2 (http://www.voila.com/)",
	"Mozilla/5.0 (Windows; U; Windows NT 5.1; fr; rv:1.8.1) VoilaBot BETA 1.2 (support.voilabot@orange-ftgroup.com)",
	"VORTEX/1.2 (+http://marty.anstey.ca/robots/vortex/)",
	"voyager/2.0 (http://www.kosmix.com/crawler.html)",
	"VWBOT/Nutch-0.9-dev (VWBOT Nutch Crawler; http://vwbot.cs.uiuc.edu; vwbot@cs.uiuc.edu)",
	"WebAlta Crawler/1.3.33 (http://www.webalta.net/ru/about_webmaster.html) (Windows; U; Windows NT 5.1; ru-RU)",
	"WebAlta Crawler/1.3.34 (http://www.webalta.net/ru/about_webmaster.html) (Windows; U; Windows NT 5.1; ru-RU)",
	"WebarooBot (Webaroo Bot; http://www.webaroo.com/rooSiteOwners.html)",
	"WebarooBot (Webaroo Bot; http://64.124.122.252/feedback.html)",
	"WebMiner (Web Miner; http://64.124.122.252/feedback.html)",
	"RufusBot (Rufus Web Miner; http://64.124.122.252/feedback.html)",
	"mozilla/5.0 (compatible; webmastercoffee/0.7; +http://webmastercoffee.com/about)",
	"WebRankSpider/1.37 (+http://ulm191.server4you.de/crawler/)",
	"Webscope/Nutch-0.9-dev (http://www.cs.washington.edu/homes/mjc/agent.html)",
	"wectar/Nutch-0.9 (nectar extracted form the glorious web; http://goosebumps4all.net/wectar; see website)",
	"wectar/Nutch-0.9 (wectar - wectar extracted from the glorious web; http://goosebumps4all.net/wectar)",
	"Willow Internet Crawler by Twotrees V2.1",
	"WinkBot/0.06 (Wink.com search engine web crawler; http://www.wink.com/Wink:WinkBot; winkbot@wink.com)",
	"WIRE/0.10 (Linux; i686; Bot,Robot,Spider,Crawler)",
	"WIRE/0.11 (Linux; i686; Bot,Robot,Spider,Crawler,aromano@cli.di.unipi.it)",
	"WIRE/0.11 (Linux; i686; Robot,Spider,Crawler,aromano@cli.di.unipi.it)",
	"Mozilla/5.0 (compatible; woriobot +http://worio.com)",
	"www.fi crawler, contact crawler@www.fi",
	"wwwster/1.4 (Beta, mailto:gue@cis.uni-muenchen.de)",
	"xirq/0.1-beta (xirq; http://www.xirq.com; xirq@xirq.com)",
	"xirq/0.1-dev (xirq; http://www.xirq.com; xirq@xirq.com)",
	"XML Sitemaps Generator 1.0",
	"Y!J-BRI/0.0.1 crawler ( http://help.yahoo.co.jp/help/jp/search/indexing/indexing-15.html )",
	"Y!J-BSC/1.0 (http://help.yahoo.co.jp/help/jp/blog-search/)",
	"Mozilla/5.0 (compatible; Yahoo! Slurp; http://help.yahoo.com/help/us/ysearch/slurp)",
	"Mozilla/5.0 (compatible; Yahoo! Slurp China; http://misc.yahoo.com.cn/help.html)",
	"Mozilla/5.0 (compatible; Yahoo! Slurp/3.0; http://help.yahoo.com/help/us/ysearch/slurp)",
	"Mozilla/5.0 (compatible; Yahoo!-AdCrawler; http://help.yahoo.com/yahoo_adcrawler)",
	"Yahoo-MMCrawler/3.x (mms dash mmcrawler dash support at yahoo dash inc dot com)",
	"Yandex/1.01.001 (compatible; Win16; P)",
	"Yandex/1.01.001 (compatible; Win16; I)",
	"Yanga WorldSearch Bot v1.1/beta (http://www.yanga.co.uk/)",
	"Yeti/1.0 (NHN Corp.; http://help.naver.com/robots/)",
	"Mozilla/5.0 (compatible; YodaoBot/1.0; http://www.yodao.com/help/webmaster/spider/; )",
	"YodaoBot/1.0 (http://www.yodao.com/help/webmaster/spider/; )",
	"Mozilla/5.0 (compatible;YodaoBot-Image/1.0;http://www.yodao.com/help/webmaster/spider/;)",
	"Mozilla/5.0 (compatible; Yoono; http://www.yoono.com/)",
	"Mozilla/5.0 (compatible; YoudaoBot/1.0; http://www.youdao.com/help/webmaster/spider/; )",
	"YowedoBot/Yowedo 1.0 (Search Engine crawler for yowedo.com; http://yowedo.com/en/partners.html; crawler@yowedo.com)",
	"ZACATEK_CZ_BOT (www.zacatek.cz)",
	"Zeusbot/0.07 (Ulysseek's web-crawling robot; http://www.zeusbot.com; agent@zeusbot.com)",
	"ZoomSpider - wrensoft.com [ZSEBOT]",
	"Mozilla/4.0 compatible ZyBorg/1.0 (wn-14.zyborg@looksmart.net; http://www.WISEnutbot.com)",
	"Mozilla/4.0 compatible ZyBorg/1.0 Dead Link Checker (wn.dlc@looksmart.net; http://www.WISEnutbot.com)",
	"Mozilla/4.0 compatible ZyBorg/1.0 (wn-16.zyborg@looksmart.net; http://www.WISEnutbot.com)");

?>

